### ISSUE TITLE
consistency in naming + fixing not working

### ISSUE THREAD

**Issue by HelenaEdlund** [AstraZeneca/blueprint#10]
Realized when using it today that in parameter() the fixing argument it is called 'fixed' and within omega_param() it is 'fix'. Can we be consistent in both arguments as well as function names for these? (on the same note, should we keep to 'nonmem'-type nomenclature (e.g. theta_param, omega_param) or more "general" nlme-type of nomenclature? 

Also: tried adding a fixed diagonal omega using omega_param(). It accepts the input but the FIX does not show up in the rendered file. Could you look into that? 

Thanks,
Helena

**Comment by dpastoor** [comment]
@HelenaEdlund Fixed on both parts. I think I got all the renaming, as had tests covering most areas.

For the omega_param just needed to update the default template

See changes https://github.com/AstraZeneca/blueprint/pull/11

Can you give that a try, and I will merge.

`remotes::install_github("astrazeneca/blueprint#11")` should install from this pull request

**Comment by HelenaEdlund** [comment]
Yup, that works now. Thanks!

**Comment by dpastoor** [comment]
fixed in f07d4a77e83b897e1c40ab55693231517c32bf57
