### ISSUE TITLE
function for adding scaling 

### ISSUE THREAD

**Issue by HelenaEdlund** [AstraZeneca/blueprint#13]
I was trying to use const() to add a scaling variable (S2 = V... ) but since it prints directly after $PK it won't run. I was thinking that we could add an option to print it last of that block instead of first but realized people may want to use both in the same file. So we should probably consider adding that as a separate function.

Thanks, 
Helena

**Comment by dpastoor** [comment]
This specific scenario might also be accomplished using hooks, let me create a PR showing my idea...

**Comment by HelenaEdlund** [comment]
Right, these software specific tweaks should be done as a last step before rendering to file. That way one keep the nice thing about being able to render to both nommem and mrgsolve. Hooks sounds like a good solution. Otherwise we would also need to build up a lot of checks and messages with things like ' this option is only supported by xxx software, being ignored'.

**Comment by dpastoor** [comment]
For now I see this as being solved by hooks per #15 , but can keep these types of scenarios in our mind and open to consideration for some software specific adaptors. 

One thing that hooks _don't_ provide is any checking, eg accidentally typing "S2 = V1" when meant "S2 = V2" or something. 

My thought is such checking (known as linting) may actually be better suited for a separate package with the sole purpose of parsing and linting. Eg checking that all parameters that should exist, do, that $TABLE statements make sense etc.
